import type {
  AppointmentTypeConfig,
  ClinicalProcedure,
  ServiceCategory,
} from "@/features/services/services.types";

export function formatEgp(amount: number): string {
  return `EGP ${amount.toLocaleString("en-US")}`;
}

export const serviceCategories: ServiceCategory[] = [
  "All",
  "Diagnostic & Preventive",
  "Restorative",
  "Endodontics",
  "Periodontics",
  "Prosthodontics",
  "Oral Surgery",
  "Orthodontics",
  "Cosmetic",
];

export const mockProcedures: ClinicalProcedure[] = [
  {
    id: "proc-001",
    code: "D0120",
    name: "Periodic Oral Evaluation",
    category: "Diagnostic & Preventive",
    defaultPrice: 350,
    durationMinutes: 20,
    active: true,
    description: "Routine examination for established patients to determine changes in dental and medical health status.",
    requiresToothTarget: false,
  },
  {
    id: "proc-002",
    code: "D0150",
    name: "Comprehensive Comprehensive Examination",
    category: "Diagnostic & Preventive",
    defaultPrice: 500,
    durationMinutes: 30,
    active: true,
    description: "Thorough initial evaluation of hard and soft tissues, charting, and treatment planning.",
    requiresToothTarget: false,
  },
  {
    id: "proc-003",
    code: "D0220",
    name: "Periapical Radiograph (Single Film)",
    category: "Diagnostic & Preventive",
    defaultPrice: 200,
    durationMinutes: 10,
    active: true,
    description: "High-resolution digital radiographic image of the crown and root apex.",
    requiresToothTarget: true,
  },
  {
    id: "proc-004",
    code: "D1110",
    name: "Dental Prophylaxis (Adult Scaling & Polishing)",
    category: "Diagnostic & Preventive",
    defaultPrice: 750,
    durationMinutes: 40,
    active: true,
    description: "Removal of supra- and subgingival plaque, calculus, and extrinsic stains.",
    requiresToothTarget: false,
  },
  {
    id: "proc-005",
    code: "D2391",
    name: "Composite Resin Restoration — 1 Surface (Posterior)",
    category: "Restorative",
    defaultPrice: 900,
    durationMinutes: 30,
    active: true,
    description: "Tooth-colored direct composite filling on one posterior tooth surface.",
    requiresToothTarget: true,
  },
  {
    id: "proc-006",
    code: "D2392",
    name: "Composite Resin Restoration — 2 Surfaces (Posterior)",
    category: "Restorative",
    defaultPrice: 1200,
    durationMinutes: 45,
    active: true,
    description: "Tooth-colored direct composite restoration on two posterior surfaces (e.g. MO, DO).",
    requiresToothTarget: true,
  },
  {
    id: "proc-007",
    code: "D3310",
    name: "Endodontic Therapy — Anterior Tooth",
    category: "Endodontics",
    defaultPrice: 2200,
    durationMinutes: 60,
    active: true,
    description: "Complete root canal treatment for anterior teeth including biomechanical instrumentation.",
    requiresToothTarget: true,
  },
  {
    id: "proc-008",
    code: "D3320",
    name: "Endodontic Therapy — Premolar",
    category: "Endodontics",
    defaultPrice: 2800,
    durationMinutes: 75,
    active: true,
    description: "Biomechanical debridement and obturation of premolar canals.",
    requiresToothTarget: true,
  },
  {
    id: "proc-009",
    code: "D3330",
    name: "Endodontic Therapy — Molar",
    category: "Endodontics",
    defaultPrice: 3800,
    durationMinutes: 90,
    active: true,
    description: "Complex root canal instrumentation and obturation of 3 or 4 molar canals.",
    requiresToothTarget: true,
  },
  {
    id: "proc-010",
    code: "D2740",
    name: "Porcelain / Ceramic Crown",
    category: "Prosthodontics",
    defaultPrice: 4200,
    durationMinutes: 60,
    active: true,
    description: "Full contour monolithic zirconia or lithium disilicate (E-max) ceramic crown.",
    requiresToothTarget: true,
  },
  {
    id: "proc-011",
    code: "D7140",
    name: "Simple Tooth Extraction",
    category: "Oral Surgery",
    defaultPrice: 850,
    durationMinutes: 30,
    active: true,
    description: "Extraction of erupted tooth or exposed root without bone removal.",
    requiresToothTarget: true,
  },
  {
    id: "proc-012",
    code: "D7210",
    name: "Surgical Tooth Extraction (Impacted/Sectioned)",
    category: "Oral Surgery",
    defaultPrice: 1800,
    durationMinutes: 50,
    active: true,
    description: "Surgical removal requiring elevation of mucoperiosteal flap and bone removal.",
    requiresToothTarget: true,
  },
  {
    id: "proc-013",
    code: "D4341",
    name: "Periodontal Scaling & Root Planing (per Quadrant)",
    category: "Periodontics",
    defaultPrice: 950,
    durationMinutes: 45,
    active: true,
    description: "Deep instrumentation of diseased root surfaces to remove bacterial toxins.",
    requiresToothTarget: false,
  },
  {
    id: "proc-014",
    code: "D9972",
    name: "In-Office Laser / LED Teeth Whitening",
    category: "Cosmetic",
    defaultPrice: 3200,
    durationMinutes: 60,
    active: true,
    description: "Chairside power bleaching session with protective gingival barrier.",
    requiresToothTarget: false,
  },
  {
    id: "proc-015",
    code: "D8080",
    name: "Orthodontic Monthly Adjustment Visit",
    category: "Orthodontics",
    defaultPrice: 650,
    durationMinutes: 30,
    active: true,
    description: "Routine archwire change, bracket repositioning, and progress review.",
    requiresToothTarget: false,
  },
];

export const mockAppointmentTypes: AppointmentTypeConfig[] = [
  {
    id: "apt-01",
    name: "General Consultation",
    category: "Diagnostic",
    defaultDurationMinutes: 20,
    defaultPrice: 350,
    color: "#0f766e",
    active: true,
    description: "Initial consultation, check-up, and preliminary diagnostic triage.",
    requiresChair: true,
  },
  {
    id: "apt-02",
    name: "Routine Cleaning & Polishing",
    category: "Preventive",
    defaultDurationMinutes: 40,
    defaultPrice: 750,
    color: "#2563eb",
    active: true,
    description: "Standard ultrasonic scaling, stain removal, and fluoride application.",
    requiresChair: true,
  },
  {
    id: "apt-03",
    name: "Root Canal Treatment",
    category: "Endodontics",
    defaultDurationMinutes: 90,
    defaultPrice: 3500,
    color: "#7c3aed",
    active: true,
    description: "Instrumentation, rotary debridement, or final canal obturation.",
    requiresChair: true,
  },
  {
    id: "apt-04",
    name: "Crown Preparation & Impression",
    category: "Prosthodontics",
    defaultDurationMinutes: 60,
    defaultPrice: 4200,
    color: "#c2410c",
    active: true,
    description: "Tooth reduction, digital intraoral scan or elastomeric impression.",
    requiresChair: true,
  },
  {
    id: "apt-05",
    name: "Surgical Extraction",
    category: "Surgery",
    defaultDurationMinutes: 45,
    defaultPrice: 1800,
    color: "#b91c1c",
    active: true,
    description: "Surgical or wisdom tooth removal under local anesthesia.",
    requiresChair: true,
  },
  {
    id: "apt-06",
    name: "Emergency / Toothache Triage",
    category: "Emergency",
    defaultDurationMinutes: 30,
    defaultPrice: 500,
    color: "#b45309",
    active: true,
    description: "Urgent pain relief, pulpotomy, incision & drainage, or temporary seal.",
    requiresChair: true,
  },
  {
    id: "apt-07",
    name: "Follow-up / Suture Removal",
    category: "Follow-up",
    defaultDurationMinutes: 15,
    defaultPrice: 0,
    color: "#475569",
    active: true,
    description: "Post-operative check, wound inspection, or suture removal.",
    requiresChair: true,
  },
  {
    id: "apt-08",
    name: "Teeth Whitening Session",
    category: "Cosmetic",
    defaultDurationMinutes: 60,
    defaultPrice: 3200,
    color: "#0891b2",
    active: true,
    description: "In-office cosmetic bleaching protocol.",
    requiresChair: true,
  },
];
