import type { ClinicalVisitRecord } from "@/features/clinical/clinical.types";

export const defaultClinicalVisit: ClinicalVisitRecord = {
  id: "VISIT-2026-0913-01",
  patientId: "P-10284",
  patientName: "Mariam Adel",
  patientAge: 38,
  patientGender: "Female",
  patientMobile: "010 1234 5678",
  allergies: ["Penicillin"],
  medicalAlerts: ["Hypertension (Stage 1) - Monitored", "Pre-medication not required"],
  appointment: {
    date: "Saturday, 13 September 2026",
    time: "14:00",
    dentist: "Dr. Karim Mostafa",
    chair: "Chair 2",
    type: "Root canal follow-up",
    status: "Confirmed",
    visitState: "In chair",
    arrivedMinutesAgo: 18,
  },
  chiefComplaint: "Follow-up after root canal therapy on upper right first molar (#16). Mild tenderness when biting earlier this week, now resolving.",
  subjectiveNotes: "Patient reports substantial relief since initial instrumentation on 8 Sep. Occasional mild ache upon mastication, no spontaneous pain or thermal sensitivity reported. Analgesic use discontinued 3 days ago.",
  objectiveFindings: "Tooth #16: Cavit temporary restoration intact and flush with margins. Percussion test: mild sensitivity (+/-). Palpation in buccal sulcus: asymptomatic, no fluctuance or vestibular swelling. Periodontal probing depths: 2-3 mm circumferentially with no bleeding on probing.",
  diagnosis: {
    primary: "Post-endodontic evaluation - Tooth #16 (Resolving apical periodontitis)",
    code: "K04.5",
    affectedTeeth: [16],
  },
  treatmentPlanRef: {
    title: "Root canal and crown restoration",
    planId: "TP-1082",
    progress: "2 of 3 procedures completed",
    nextPlannedStep: "Final crown preparation & impression (Tooth #16)",
  },
  treatmentsPerformed: [
    {
      id: "proc-1",
      procedure: "Canal debridement and irrigation",
      tooth: 16,
      anesthesia: "Infiltration: Mepivacaine 3% (Plain - 1.8 mL)",
      materials: "NaOCl 2.5%, EDTA 17%, sterile saline flush",
      notes: "Canals irrigated, dried with sterile paper points. No exudate present.",
      cost: 650,
    },
    {
      id: "proc-2",
      procedure: "Intracanal medication and temporary restoration",
      tooth: 16,
      materials: "Calcium hydroxide paste (Ca(OH)2), Cavit G temporary seal",
      notes: "Intracanal dressing replaced. Cavit seal verified intact.",
      cost: 800,
    },
  ],
  prescriptions: "No antibiotics prescribed due to Penicillin allergy and absence of acute systemic infection. Ibuprofen 400mg PO PRN for mild discomfort (max 1200mg/day).",
  nextVisitRecommendation: "Return in 10-14 days for permanent obturation or crown prep assessment.",
  attachments: [
    {
      id: "att-01",
      title: "Periapical X-ray - Tooth 16 (Working length)",
      type: "image/jpeg",
      size: "1.8 MB",
      date: "08 Sep 2026",
      category: "X-Ray",
    },
    {
      id: "att-02",
      title: "Pre-operative Diagnostic Radiograph",
      type: "image/jpeg",
      size: "2.4 MB",
      date: "30 Aug 2026",
      category: "X-Ray",
    },
    {
      id: "att-03",
      title: "Signed Endodontic Consent Form",
      type: "application/pdf",
      size: "412 KB",
      date: "30 Aug 2026",
      category: "Consent",
    },
  ],
  selectedTooth: 16,
  status: "In progress",
  amendments: [],
};

export const commonDiagnoses = [
  "Post-endodontic evaluation - Tooth #16 (Resolving apical periodontitis)",
  "Pulp necrosis with symptomatic apical periodontitis",
  "Irreversible pulpitis with normal apical tissues",
  "Dental caries penetrating dentin",
  "Secondary caries under existing restoration",
  "Chronic generalized plaque-induced gingivitis",
  "Localized stage II periodontitis",
  "Fractured tooth cusp / cracked tooth syndrome",
  "Defective margin on existing porcelain crown",
];

export const commonProcedures = [
  "Canal debridement and irrigation",
  "Intracanal medication and temporary restoration",
  "Complete endodontic obturation (gutta-percha & sealer)",
  "Direct composite restoration (Class II)",
  "Direct composite restoration (Class I)",
  "Full ceramic crown preparation & impression",
  "Prophylaxis, scaling & root planing (quadrant)",
  "Periapical diagnostic digital radiograph",
];
