import { Banknote, CalendarCheck2, CircleDollarSign, Clock3, PackageSearch, UsersRound } from "lucide-react";
import type { DashboardConfig } from "@/features/dashboard/dashboard.types";
import type { UserRole } from "@/types";

export const dashboardUsers: Record<UserRole, string> = { admin: "Dr. Salma Hassan", receptionist: "Nour Adel", dentist: "Dr. Karim Mostafa" };

const configs: Record<UserRole, DashboardConfig> = {
  admin: { role: "admin", title: "Good morning, Dr. Salma", description: "Here is the clinic at a glance for Saturday, 13 September.", metrics: [{ label: "Today's appointments", value: "28", detail: "6 remaining", tone: "primary", icon: CalendarCheck2 }, { label: "Waiting patients", value: "4", detail: "Longest wait: 18 min", tone: "warning", icon: UsersRound }, { label: "Completed visits", value: "17", detail: "61% of today's schedule", tone: "success", icon: Clock3 }, { label: "Today's revenue", value: "EGP 18,450", detail: "EGP 6,200 outstanding", tone: "neutral", icon: CircleDollarSign }], appointments: [{ time: "14:00", patient: "Mariam Adel", service: "Root canal follow-up", dentist: "Dr. Karim", appointmentStatus: "Confirmed", visitState: "Waiting" }, { time: "14:30", patient: "Omar Nabil", service: "Consultation", dentist: "Dr. Salma", appointmentStatus: "Confirmed", visitState: "Not arrived" }, { time: "15:00", patient: "Laila Ahmed", service: "Crown fitting", dentist: "Dr. Karim", appointmentStatus: "Booked", visitState: "Not arrived" }, { time: "15:30", patient: "Youssef Tarek", service: "Cleaning", dentist: "Dr. Salma", appointmentStatus: "Confirmed", visitState: "Not arrived" }] },
  receptionist: { role: "receptionist", title: "Good morning, Nour", description: "Four patients are waiting. Your next appointment begins in 12 minutes.", metrics: [{ label: "Today's appointments", value: "28", detail: "6 remaining", tone: "primary", icon: CalendarCheck2 }, { label: "Waiting queue", value: "4", detail: "2 awaiting check-in", tone: "warning", icon: UsersRound }, { label: "Check-ins today", value: "21", detail: "75% of today's schedule", tone: "success", icon: Clock3 }, { label: "Open balances", value: "EGP 6,200", detail: "9 patients", tone: "neutral", icon: Banknote }], appointments: [{ time: "14:00", patient: "Mariam Adel", service: "Root canal follow-up", dentist: "Dr. Karim", appointmentStatus: "Confirmed", visitState: "Waiting" }, { time: "14:30", patient: "Omar Nabil", service: "Consultation", dentist: "Dr. Salma", appointmentStatus: "Confirmed", visitState: "Not arrived" }, { time: "15:00", patient: "Laila Ahmed", service: "Crown fitting", dentist: "Dr. Karim", appointmentStatus: "Booked", visitState: "Not arrived" }] },
  dentist: { role: "dentist", title: "Good morning, Dr. Karim", description: "You have three patients remaining today. Mariam Adel is ready for her visit.", metrics: [{ label: "Today's schedule", value: "9", detail: "3 remaining", tone: "primary", icon: CalendarCheck2 }, { label: "Waiting patients", value: "1", detail: "Mariam Adel · 18 min", tone: "warning", icon: UsersRound }, { label: "Visits completed", value: "6", detail: "2 clinical notes to finalize", tone: "success", icon: Clock3 }, { label: "Plans needing attention", value: "3", detail: "1 ready to approve", tone: "neutral", icon: PackageSearch }], appointments: [{ time: "14:00", patient: "Mariam Adel", service: "Root canal follow-up", appointmentStatus: "Confirmed", visitState: "Waiting" }, { time: "15:00", patient: "Laila Ahmed", service: "Crown fitting", appointmentStatus: "Booked", visitState: "Not arrived" }, { time: "16:00", patient: "Hana Youssef", service: "Treatment review", appointmentStatus: "Confirmed", visitState: "Not arrived" }] },
};

export function getMockDashboard(role: UserRole) { return configs[role]; }
