import type { AuditEvent } from "@/features/audit-logs/audit-logs.types";

export const mockAuditEvents: AuditEvent[] = [
  {
    id: "audit-001",
    timestamp: "13 Sep 2026 · 14:02",
    user: "Dr. Karim Mostafa",
    userRole: "dentist",
    action: "Clinical record viewed",
    module: "Clinical",
    entity: "Mariam Adel",
    entityId: "patient-001",
    result: "Success",
    detail: "Dentist opened the clinical record for Mariam Adel during an active visit. This access is within normal operating scope.",
    ipAddress: "192.168.1.45",
  },
  {
    id: "audit-002",
    timestamp: "13 Sep 2026 · 14:05",
    user: "Dr. Karim Mostafa",
    userRole: "dentist",
    action: "Clinical attachment downloaded",
    module: "Clinical",
    entity: "Mariam Adel — Periapical X-ray",
    entityId: "attachment-xray-2026-0901",
    result: "Success",
    detail: "Dentist downloaded a periapical X-ray image attached to the patient clinical record. File: xray_mariam_adel_2026_09_01.jpg.",
    ipAddress: "192.168.1.45",
  },
  {
    id: "audit-003",
    timestamp: "13 Sep 2026 · 11:47",
    user: "Dr. Salma Hassan",
    userRole: "admin",
    action: "Admin override — booking conflict",
    module: "Appointments",
    entity: "Chair 2 · 13 Sep 2026 · 14:30",
    entityId: "apt-override-0913",
    result: "Warning",
    detail: "Admin overrode a scheduling conflict to book Laila Ahmed in Chair 2 at 14:30. Override reason recorded: \"Patient travelling from Giza; only available slot.\"",
    ipAddress: "192.168.1.10",
  },
  {
    id: "audit-004",
    timestamp: "13 Sep 2026 · 10:22",
    user: "Dr. Salma Hassan",
    userRole: "admin",
    action: "Invoice voided",
    module: "Billing",
    entity: "INV-0987",
    entityId: "INV-0987",
    result: "Success",
    detail: "Admin voided invoice INV-0987 (Omar Nabil, EGP 1,800). Reason: duplicate invoice created by system error. Financial correction logged as immutable entry.",
    ipAddress: "192.168.1.10",
  },
  {
    id: "audit-005",
    timestamp: "12 Sep 2026 · 16:38",
    user: "Nour Adel",
    userRole: "receptionist",
    action: "Partial payment recorded",
    module: "Billing",
    entity: "INV-1004 — Omar Nabil",
    entityId: "INV-1004",
    result: "Success",
    detail: "Receptionist recorded a partial cash payment of EGP 1,500 against INV-1004 (total EGP 3,000). Remaining balance: EGP 1,500.",
    ipAddress: "192.168.1.22",
  },
  {
    id: "audit-006",
    timestamp: "12 Sep 2026 · 15:10",
    user: "Dr. Salma Hassan",
    userRole: "admin",
    action: "Write-off applied",
    module: "Billing",
    entity: "INV-0965 — Laila Ahmed",
    entityId: "INV-0965",
    result: "Warning",
    detail: "Admin applied a write-off of EGP 200 to INV-0965. This reduces the collectible balance without issuing a refund. Immutable record created.",
    ipAddress: "192.168.1.10",
  },
  {
    id: "audit-007",
    timestamp: "13 Sep 2026 · 09:42",
    user: "Dr. Salma Hassan",
    userRole: "admin",
    action: "Stock adjustment recorded",
    module: "Inventory",
    entity: "Nitrile examination gloves",
    entityId: "inv-gloves",
    result: "Success",
    detail: "Admin decreased stock of Nitrile examination gloves by 8 pairs. Reason: damaged stock removed. New balance: 42 pairs. Movement ID: movement-001.",
    ipAddress: "192.168.1.10",
  },
  {
    id: "audit-008",
    timestamp: "13 Sep 2026 · 11:18",
    user: "Dr. Salma Hassan",
    userRole: "admin",
    action: "Goods receipt recorded",
    module: "Inventory",
    entity: "Patient rinse cups",
    entityId: "inv-cups",
    result: "Success",
    detail: "Admin recorded a goods receipt of 12 packs of Patient rinse cups from Medline Supplies. New balance: 24 packs.",
    ipAddress: "192.168.1.10",
  },
  {
    id: "audit-009",
    timestamp: "13 Sep 2026 · 08:15",
    user: "Dr. Salma Hassan",
    userRole: "admin",
    action: "Reports exported (CSV)",
    module: "Reports",
    entity: "Appointment status report — 13 Sep 2026",
    result: "Success",
    detail: "Admin triggered a CSV export of the appointment status breakdown report for 13 Sep 2026. Export includes 28 appointment records.",
    ipAddress: "192.168.1.10",
  },
  {
    id: "audit-010",
    timestamp: "13 Sep 2026 · 08:00",
    user: "Dr. Salma Hassan",
    userRole: "admin",
    action: "Login successful",
    module: "Auth",
    entity: "Admin account",
    result: "Success",
    detail: "Admin authenticated with email and password. MFA TOTP code verified successfully. Session started.",
    ipAddress: "192.168.1.10",
  },
  {
    id: "audit-011",
    timestamp: "12 Sep 2026 · 23:44",
    user: "Unknown",
    userRole: "admin",
    action: "Login failed — account locked",
    module: "Auth",
    entity: "salma@smileclinic.example",
    result: "Denied",
    detail: "Five consecutive failed login attempts for salma@smileclinic.example. Account temporarily locked for 30 minutes per security policy. IP flagged.",
    ipAddress: "41.65.200.12",
  },
  {
    id: "audit-012",
    timestamp: "12 Sep 2026 · 09:30",
    user: "Nour Adel",
    userRole: "receptionist",
    action: "Login successful",
    module: "Auth",
    entity: "Receptionist account",
    result: "Success",
    detail: "Receptionist authenticated with email and password. No MFA required for this role.",
    ipAddress: "192.168.1.22",
  },
  {
    id: "audit-013",
    timestamp: "11 Sep 2026 · 17:05",
    user: "Dr. Karim Mostafa",
    userRole: "dentist",
    action: "Clinical record finalized",
    module: "Clinical",
    entity: "Hana Youssef — Visit 11 Sep 2026",
    entityId: "visit-hana-0911",
    result: "Success",
    detail: "Dentist finalized the clinical record for Hana Youssef's visit on 11 Sep 2026. Record is now immutable. Diagnosis: Mild periodontal disease.",
    ipAddress: "192.168.1.45",
  },
  {
    id: "audit-014",
    timestamp: "11 Sep 2026 · 14:22",
    user: "Dr. Salma Hassan",
    userRole: "admin",
    action: "Settings updated — appointment rules",
    module: "Settings",
    entity: "Appointment rules configuration",
    result: "Success",
    detail: "Admin updated appointment rules: default slot changed from 20 to 30 minutes, cancellation cut-off set to 24 hours.",
    ipAddress: "192.168.1.10",
  },
  {
    id: "audit-015",
    timestamp: "10 Sep 2026 · 11:00",
    user: "Nour Adel",
    userRole: "receptionist",
    action: "Clinical record access denied",
    module: "Clinical",
    entity: "Mariam Adel — clinical notes",
    entityId: "patient-001",
    result: "Denied",
    detail: "Receptionist attempted to access detailed clinical notes for Mariam Adel. Access denied per role-based access control policy. Receptionists may not view clinical notes or diagnoses.",
    ipAddress: "192.168.1.22",
  },
];
